name: ESLint
on: [push, pull_request]

jobs:
  run-eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Lint
        run: yarn lint --max-warnings=0
