name: Prettier
on: [push, pull_request]

jobs:
  run-prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Prettier Check
        run: yarn check
